version: "3"

services: 
  website:
    container_name: website
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - caddy
  
  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
    networks:
      - caddy
  
networks:
  caddy:
    external: true